name: frontend-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create .env.local
        working-directory: olympna-frontend
        run: |
          echo "NEXT_PUBLIC_STRAPI_API_URL=${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }}" >> .env.local
          echo "NEXT_PUBLIC_STRAPI_MEDIA_URL=${{ secrets.NEXT_PUBLIC_STRAPI_MEDIA_URL }}" >> .env.local
          echo "NEXT_PUBLIC_STRAPI_TOKEN=${{ secrets.NEXT_PUBLIC_STRAPI_TOKEN }}" >> .env.local

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: olympna-frontend
        run: npm ci

      - name: Lint
        working-directory: olympna-frontend
        run: npm run lint

      - name: Type Check
        working-directory: olympna-frontend
        run: npm run type-check || true

      - name: Build
        working-directory: olympna-frontend
        run: npm run build
